// collision
#external
pub type B2AABB
#external
pub type B2Bound
#external
pub type B2BoundValues
#external
pub type B2BroadPhase
#external
pub type B2BufferedPair
#external
pub type B2Collision
#external
pub type B2ContactID
#external
pub type B2ContactPoint
#external
pub type B2Distance
#external
pub type B2Manifold
#external
pub type B2OBB
#external
pub type B2Pair
#external
pub type B2PairCallback
#external
pub type B2PairManager
#external
pub type B2Proxy
#external
pub type ClipVertex
#external
pub type Features

// collision/shape
#external
pub type B2BoxDef
#external
pub type B2BoxShape
#external
pub type B2CircleDef
#external
pub type B2CircleShape
#external
pub type B2MassData
#external
pub type B2PolygonDef
#external
pub type B2PolygonShape
#external
pub type B2Shape
#external
pub type B2ShapeDef

// common/math
#external
pub type B2Mat22
#external
pub type B2Vec2

// dynamics
#external
pub type B2Body
#external
pub type B2BodyDef
#external
pub type B2TimeStep
#external
pub type B2World_
#external
pub type B2WorldListener

// dynamics/contacts
#external
pub type B2CircleContact
#external
pub type B2Conservative
#external
pub type B2Contact
#external
pub type B2ContactConstraint
#external
pub type B2ContactConstraintPoint
#external
pub type B2ContactNode
#external
pub type B2ContactRegister
#external
pub type B2ContactSolver
#external
pub type B2NullContact
#external
pub type B2PolyAndCircleContact
#external
pub type B2PloyContact


// dynamic/joints
#external
pub type B2DistanceJoint
#external
pub type B2DistanceJointDef
#external
pub type B2GearJoint
#external
pub type B2GearJointDef
#external
pub type B2Jacobian
#external
pub type B2Joint
#external
pub type B2JointDef
#external
pub type B2JointNode
#external
pub type B2MouseJoint
#external
pub type B2MouseJointDef
#external
pub type B2PrismaticJoint
#external
pub type B2PrismaticJointDef
#external
pub type B2PulleyJoint
#external
pub type B2PulleyJointDef
#external
pub type B2RevoluteJoint
#external
pub type B2RevoluteJointDef
#external
pub type B2SpringJoint
#external
pub type B2SpringJointDef
#external
pub type B2CollisionFilter

