const CONTENT : String = 
#|{
#|  "world_settings": {
#|    "gravity": [
#|      0,
#|      -9.8
#|    ],
#|    "allow_sleeping": true,
#|    "auto_clear_forces": true
#|  },
#|  "bodies": [
#|    {
#|      "id": "body_1760510312934_m73h9iums",
#|      "body_def": {
#|        "type": "dynamic",
#|        "position": [
#|          0.4166664123535153,
#|          11.333333587646486
#|        ],
#|        "angle": 0,
#|        "linear_velocity": [
#|          0,
#|          0
#|        ],
#|        "angular_velocity": 0,
#|        "linear_damping": 0,
#|        "angular_damping": 0,
#|        "allow_sleep": true,
#|        "awake": true,
#|        "fixed_rotation": false,
#|        "bullet": false,
#|        "gravity_scale": 1
#|      },
#|      "fixtures": [
#|        {
#|          "shape": {
#|            "type": "box",
#|            "params": {
#|              "width": 1,
#|              "height": 1
#|            }
#|          },
#|          "fixture_def": {
#|            "density": 1,
#|            "friction": 0.3,
#|            "restitution": 0.5,
#|            "is_sensor": false,
#|            "filter_category_bits": 1,
#|            "filter_mask_bits": 65535,
#|            "filter_group_index": 0
#|          }
#|        }
#|      ],
#|      "visual_properties": {},
#|      "user_data": {}
#|    }
#|  ],
#|  "joints": []
#|}