pub let sword_body:String=
#|{
#|	"id": "body_1760536199757_75cvmdoa7",
#|	"body_def": {
#|		"type": "dynamic",
#|		"position": [
#|			-6.335077519379845,
#|			16.96435594294783
#|		],
#|		"angle": 0,
#|		"linear_velocity": [
#|			0,
#|			0
#|		],
#|		"angular_velocity": 0,
#|		"linear_damping": 0,
#|		"angular_damping": 0,
#|		"allow_sleep": true,
#|		"awake": true,
#|		"fixed_rotation": false,
#|		"bullet": false,
#|		"gravity_scale": 1
#|	},
#|	"fixtures": [
#|		{
#|			"shape": {
#|				"type": "polygon",
#|				"params": {
#|					"vertices": [
#|						[
#|							-0.42,
#|							-1.13
#|						],
#|						[
#|							-0.32,
#|							-1.13
#|						],
#|						[
#|							-0.26,
#|							1.35
#|						],
#|						[
#|							-0.5,
#|							1.11
#|						],
#|						[
#|							-0.43,
#|							-0.6187499999999995
#|						],
#|						[
#|							-0.63,
#|							-0.75
#|						],
#|						[
#|							-0.57,
#|							-0.82
#|						],
#|						[
#|							-0.41,
#|							-0.75
#|						]
#|					]
#|				}
#|			},
#|			"fixture_def": {
#|				"density": 0.01,
#|				"friction": 0.3,
#|				"restitution": 0.5,
#|				"is_sensor": false,
#|				"filter_category_bits": 1,
#|				"filter_mask_bits": 65535,
#|				"filter_group_index": -1
#|			}
#|		}
#|	],
#|	"visual_properties": {},
#|	"user_data": {}
#|}


pub let gun_body:String=
#| {
#|       "id": "body_1760795953628_lylo5ag1a",
#|       "body_def": {
#|         "type": "dynamic",
#|         "position": [
#|           12.904793874424993,
#|           14.748299439064441
#|         ],
#|         "angle": 0,
#|         "linear_velocity": [
#|           0,
#|           0
#|         ],
#|         "angular_velocity": 0,
#|         "linear_damping": 0,
#|         "angular_damping": 0,
#|         "allow_sleep": true,
#|         "awake": true,
#|         "fixed_rotation": false,
#|         "bullet": false,
#|         "gravity_scale": 1
#|       },
#|       "fixtures": [
#|         {
#|           "shape": {
#|             "type": "box",
#|             "params": {
#|               "width": 0.5,
#|               "height": 1
#|             }
#|           },
#|           "fixture_def": {
#|             "density": 0.01,
#|             "friction": 0.3,
#|             "restitution": 0.5,
#|             "is_sensor": false,
#|             "filter_category_bits": 1,
#|             "filter_mask_bits": 65535,
#|             "filter_group_index": -1
#|           }
#|         }
#|       ],
#|       "visual_properties": {},
#|       "user_data": {}
#|     }
		