pub const BOXENEMY_BOX2D_DEFINITION =
#|  {
#|    "id": "body_1760796142791_lkc815e42",
#|    "body_def": {
#|      "type": "dynamic",
#|      "position": [
#|        0.0019317231832161053,
#|        0.00704536356294827
#|      ],
#|      "angle": 0,
#|      "linear_velocity": [
#|        0,
#|        0
#|      ],
#|      "angular_velocity": 0,
#|      "linear_damping": 0,
#|      "angular_damping": 0,
#|      "allow_sleep": true,
#|      "awake": true,
#|      "fixed_rotation": false,
#|      "bullet": false,
#|      "gravity_scale": 1
#|    },
#|    "fixtures": [
#|      {
#|        "shape": {
#|          "type": "box",
#|          "params": {
#|            "width": 2.0434781361455583,
#|            "height": 1.9999998256138543
#|          }
#|        },
#|        "fixture_def": {
#|          "density": 1,
#|          "friction": 0.3,
#|          "restitution": 0.5,
#|          "is_sensor": false,
#|          "filter_category_bits": 1,
#|          "filter_mask_bits": 65535,
#|          "filter_group_index": 0
#|        }
#|      }
#|    ],
#|    "visual_properties": {},
#|    "user_data": {}
#|  }