// collision
#external
type B2AABB
#external
type B2Bound
#external
type B2BoundValues
#external
type B2BroadPhase
#external
type B2BufferedPair
#external
type B2Collision
#external
type B2ContactID
#external
type B2ContactPoint
#external
type B2Distance
#external
type B2Manifold
#external
type B2OBB
#external
type B2Pair
#external
type B2PairCallback
#external
type B2PairManager
#external
type B2Proxy
#external
type ClipVertex
#external
type Features

// collision/shape
#external
type B2BoxDef
#external
type B2BoxShape
#external
type B2CircleDef
#external
type B2CircleShape
#external
type B2MassData
#external
type B2PolygonDef
#external
type B2PolygonShape
#external
type B2Shape
#external
type B2ShapeDef

// common/math
#external
type B2Mat22
#external
type B2Vec2

// dynamics
#external
type B2Body
#external
type B2BodyDef
#external
type B2TimeStep
#external
type B2World_
#external
type B2WorldListener

// dynamics/contacts
#external
type B2CircleContact
#external
type B2Conservative
#external
type B2Contact
#external
type B2ContactConstraint
#external
type B2ContactConstraintPoint
#external
type B2ContactNode
#external
type B2ContactRegister
#external
type B2ContactSolver
#external
type B2NullContact
#external
type B2PolyAndCircleContact
#external
type B2PloyContact


// dynamic/joints
#external
type B2DistanceJoint
#external
type B2DistanceJointDef
#external
type B2GearJoint
#external
type B2GearJointDef
#external
type B2Jacobian
#external
type B2Joint
#external
type B2JointDef
#external
type B2JointNode
#external
type B2MouseJoint
#external
type B2MouseJointDef
#external
type B2PrismaticJoint
#external
type B2PrismaticJointDef
#external
type B2PulleyJoint
#external
type B2PulleyJointDef
#external
type B2RevoluteJoint
#external
type B2RevoluteJointDef
#external
type B2SpringJoint
#external
type B2SpringJointDef
#external
type B2CollisionFilter

